Person.id=123
Person.name=Thari
Person.age=18
Person.langs=English,Tamil,Baduga

Address.addrId=23
Address.city=cbe
Address.state=TamilNadu

Employee.eid=345
Employee.ename=roja

Department.did=2
Department.dname=Accounts


Student.sid=890
Student.sname=Raj

Course.cid=258
Course.cname=Java